# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5ab1c08ae61067f085735f99aba896c52906c77dadb04ab0598cd1b2dc2847b3691af2b3babb98c10674de1284349629bc20240f9a9eb93b182ded113d62113

test:
  secret_key_base: 4dba2fdb8adf4e61dfa1390b1bff4f977a89e7dceda6f22983eeee1259ac91b5db8df09a75aca6bcab638413931734f1dd1151fe08603ac0db1dd7dba1c609f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
